### ISSUE TITLE
[Bug] 背景zmc后没有保持

### ISSUE THREAD

**Issue by ourandream** [ba-archive/blue-archive#114]
### 问题描述

zmc后应该保持而不是突然变回原来比例
现在表现

https://github.com/ba-archive/blue-archive/assets/71924104/e0f4cd40-1949-46a4-a241-8882ebb76e41

实际
https://www.bilibili.com/video/BV11V411G7r3?t=235.2&p=2

### 问题位置

https://feat-newchapter.bluearchive.pages.dev/archive/10074/story/100743 l2d后

**Comment by diyigemt** [comment]
story那边有什么说法吗，因为zmc保持是需要一直有zmc这个标签的，不会是nx改了吧
