### ISSUE TITLE
[Enhancement] 文字出现速度、自动模式下播放完成等待时间略微延长

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#118]
### 功能描述

其次，自动播放的速度稍微有些快了，我对比了一下日服和国服，不管是出字和是停顿都要比游戏内更快一些，我个人会跟不上

~~，所以也希望能出一个调节速度的功能，就像galgame一样。~~

**Comment by diyigemt** [comment]
调节速度做播放器菜单里?

**Comment by Mark9804** [comment]
可以啊
