### ISSUE TITLE
[Bug] 全屏时播放器界面无法覆盖屏幕（系统无关）

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#119]
### 问题描述

剧情站的朋友你们好，前天在评论区提出了关于全屏小小的建议，现在来回复一下。首先是全屏，网站的全屏功能不能自动对齐屏幕边框，上下和左右都没有铺满，导致四周都有黑边，画面被一个黑色的方框框住了，初见有点不舒服。如果画面能够上下对齐电脑屏幕，只有左右两边留有黑边填充屏幕就好了。我使用的是chrome浏览器，电脑屏幕比例是1920x1080。

我的操作系统是：Windows 10 家庭中文版 版本号 22H2，使用的chrome版本是115.0.5790.110（正式版本） （64 位），使用的firefox版本是116.0 (64 位)。测试结果是，Firefox会出现同样的无法铺满屏幕的问题，跟chrome相比较，画面大小是一模一样的。有一点其他发现，就是Firefox的UI右上角按钮会更大，字体会更粗一些。

### 问题位置

--

**Comment by Mark9804** [comment]
我觉得应该让播放器监听高度变化

**Comment by xiaofeiTM233** [comment]
个人认为还是和系统有关？

一台WIN7的电脑切换分辨率后任何分辨率都能正常全屏
![image](https://github.com/ba-archive/blue-archive/assets/55832499/7ee88470-2f1c-4a74-bae3-39740680e521)
↑采用远程控制的方式控制分辨率
另几台win10的电脑切换分辨率后任何分辨率都不能正常全屏
![image](https://github.com/ba-archive/blue-archive/assets/55832499/f20616ba-c25d-41c4-83a1-102431d25698)
↑确保不影响分辨率，采用远程再远程控制分辨率
![image](https://github.com/ba-archive/blue-archive/assets/55832499/1808d964-1364-483f-b10e-75797a470376)

已经不记得是什么时候的问题了，后面我是手动放大到110%暂时处理的
在之前，屏幕分辨率不会影响全屏（只是右边滚动栏挡了一部分，解决过了）
如果这个问题大家都能复现那就说明还是有问题了
如果有空还是麻烦研究一下了

**Comment by Mark9804** [comment]
我觉得有可能是可以主动隐藏状态栏的系统都会触发这个问题

总之多加两个监听去做这件事
