### ISSUE TITLE
[Bug] Edge 异常卡顿？

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#124]
### 问题描述

我是使用电脑端看的，配置的话是Ryzen5 1600x GTX1080 内存16g，目前使用的是Edge浏览器，版本号为：115.0.1901.200

不是某一段剧情 我整个操作页面都很卡顿 点击一句话要等大概4-5秒才能出下一句

### 问题位置

全站

**Comment by Mark9804** [comment]
我拿Windows复现不出

**Comment by xiaofeiTM233** [comment]
是这种情况吗，字是一个一个缓慢出的

https://github.com/ba-archive/blue-archive/assets/55832499/195cc83e-ce8d-49c3-87f2-17f2870d6b14

被控端Ryzen 7950x 无显卡
测试chrome表现一样
开不开硬件加速都是这个表现，因为没有显卡
并且全屏也有边框

**Comment by Mark9804** [comment]
用户没开硬件加速，现在已经变成 chrome 的形状了
