### ISSUE TITLE
[Enhancement] 绑定鼠标滚轮操作

### ISSUE THREAD

**Issue by ShinonomeSetsuna** [ba-archive/blue-archive#127]
### 功能描述

将滚轮下滑视为鼠标左键点击，上滑直接调出历史记录
虽然用户主要是手机端但是感觉加上也不错（x

**Comment by Mark9804** [comment]
https://github.com/ba-archive/blue-archive/commit/4fb7b55b4654ca81dac6cb8c73f57c0407144188

https://github.com/ba-archive/blue-archive/blob/dev/lib/ba-story-player/lib/layers/uiLayer/userInteract.ts#L59

可以自行仿写提PR
