### ISSUE TITLE
[Bug] 刷新页面后<html>标签丢失暗/亮色主题属性

### ISSUE THREAD

**Issue by xiaofeiTM233** [ba-archive/blue-archive#131]
### 问题描述

刷新后<html>标签中丢失data-theme属性

### 问题位置

.

### 复现流程

刷新一次网页

**Comment by xiaofeiTM233** [comment]
追溯了一下 似乎是这里 https://github.com/ba-archive/blue-archive/commit/3d2aa03897bc16808b52e47da15402cd3b8e4818
感觉是解决的方式错了
修复前 vs 修复后
![image](https://github.com/ba-archive/blue-archive/assets/55832499/7dd92f3c-eb0b-4b57-8a1f-d1e6ad97c53d)![image](https://github.com/ba-archive/blue-archive/assets/55832499/41c32b61-9bc7-44c5-8f4c-9fe6b7e26aeb)
修复前是移动端需要点开菜单时才会同步暗/亮色偏好（因为同步偏好的功能在菜单的vue里），修复后直接把同步解决掉了？
那这是什么修复（

可以有几种解决方案：

1. 不再同步偏好，加上切换按钮复位的功能
2. 把同步偏好提前到App.vue里

**Comment by Mark9804** [comment]
哦 我调试的时候注释掉了代码忘记反注释回来了

**Comment by xiaofeiTM233** [comment]
仍然没有修复移动端无法直接同步暗/亮色偏好的问题

**Comment by Mark9804** [comment]
这下测了应该可以了
