### ISSUE TITLE
[Bug] 水mimori l2d没声音

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#138]
### 问题描述

https://preview.blue-archive.io/archive/20029/story/200295

刚刚试了一下邮箱的l2d有声音，可能是语音文件出问题了？

### 问题位置

https://preview.blue-archive.io/archive/20029/story/200295

**Comment by Mark9804** [comment]
文件没问题

**Comment by xiaofeiTM233** [comment]
有声音啊
