### ISSUE TITLE
[Enhancement] 在长时间播放未完成时提供选项强行继续播放

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/blue-archive#139]
### 功能描述

字面意思，反正有播放器内设置了，加个开关允许不知道为什么就突然长时间未完成后继续播放

### 具体操作

1. 打开冰箱门
2. 把大象放进去
3. 关上冰箱门

**Comment by diyigemt** [comment]
缺ui

**Comment by Mark9804** [comment]
呜呜好

**Comment by Mark9804** [comment]
这个功能应该叫他什么啊

**Comment by diyigemt** [comment]
不...不知道

**Comment by Mark9804** [comment]
投降，投降喵
<img width="719" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/fc3b4bbd-fb9b-485b-a6f4-494911f18396">

**Comment by Mark9804** [comment]
这个做了吗

**Comment by diyigemt** [comment]
当时琢磨了很久，到底要怎么强行继续播放，没琢磨出来

**Comment by Mark9804** [comment]
夸夸，这个可能要做全局的 try catch，根据我们内部的错误码决定是可继续的 exception 还是不可恢复的 fatal error

**Comment by Mark9804** [comment]
所以就放到新架构里面吧，旧架构都已经这样了

**Comment by diyigemt** [comment]
夸夸
