### ISSUE TITLE
[Enhancement] 允许调节文字速度

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/blue-archive#144]
### 功能描述

在播放器内菜单允许用户调节文字速度
#118 

### 具体操作

1. 打开冰箱门
2. 把大象放进去
3. 关上冰箱门

**Comment by diyigemt** [comment]
缺ui

**Comment by Mark9804** [comment]
文字速度那个数字是什么意思来着，每个字停顿多少毫秒吗

**Comment by Mark9804** [comment]
<img width="887" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/884b2a09-493d-43e3-9da5-d7659c2c234f">
