### ISSUE TITLE
[Bug] 剧情播放在 Chrome Dev 上播放非常缓慢

### ISSUE THREAD

**Issue by Namorzyny** [ba-archive/blue-archive#150]
### 问题描述

版本：Chrome Dev `118.0.5979.2（Official Build）dev （64 ビット）`
描述：播放非常缓慢。控制台能看到元素以差不多一秒一次的速度刷新。在 Edge `116.0.1938.69 (公式ビルド) (64 ビット) `中播放正常。
日志：Console 没有输出任何日志

### 问题位置

https://blue-archive.io/archive/10068/story/100682

**Comment by xiaofeiTM233** [comment]
先来确认一下，请检查浏览器是否开启硬件加速
如果有独显，打开任务管理器看看浏览器是不是调用的独显
![image](https://github.com/ba-archive/blue-archive/assets/55832499/f2437bce-9bf2-4245-baa6-2abf36ff660b)

**Comment by Mark9804** [comment]
感觉是没有正确调用 GPU，麻烦检查一下硬件加速功能是否开启，以及其他网页（例： https://www.aten7.com/ ）能否正常调用 GPU

**Comment by xiaofeiTM233** [comment]
![image](https://github.com/ba-archive/blue-archive/assets/55832499/30197655-133f-4aeb-8f19-df8ebb3cb90b)
![image](https://github.com/ba-archive/blue-archive/assets/55832499/2cbae0c6-7448-4e19-83f1-02b5123cc6fe)
经测，该版本正常，非chrome错误

**Comment by Mark9804** [comment]
麻烦尝试一下关闭并重新开启 chrome dev 的硬件加速功能

**Comment by Namorzyny** [comment]
> 麻烦尝试一下关闭并重新开启 chrome dev 的硬件加速功能

这边无论是否开启硬件加速看起来都是一样的效果

**Comment by Namorzyny** [comment]
不好意思是我的锅，不小心打开了自己的 UserScript 劫持了 `Date.now` 导致的精度下降造成的（限制在了 1s（

**Comment by xiaofeiTM233** [comment]
一个小问题，确认一下，是国人吗（
看资料都是日文以为是日本人

**Comment by Namorzyny** [comment]
> 一个小问题，确认一下，是国人吗（ 看资料都是日文以为是日本人

是的 🤣

**Comment by Mark9804** [comment]
> 不好意思是我的锅，不小心打开了自己的 UserScript 劫持了 `Date.now` 导致的精度下降造成的（限制在了 1s（

能给一下脚本地址吗，群友纷纷表示居然还有这种操作

**Comment by xiaofeiTM233** [comment]
> 能给一下脚本地址吗，群友纷纷表示居然还有这种操作

也许是这玩意儿？[![image](https://github.com/ba-archive/blue-archive/assets/55832499/19cfcba8-23b9-4ae2-a473-0b7f430df3a4)](https://timer.palerock.cn/)

**Comment by Namorzyny** [comment]
> > 不好意思是我的锅，不小心打开了自己的 UserScript 劫持了 `Date.now` 导致的精度下降造成的（限制在了 1s（
> 
> 能给一下脚本地址吗，群友纷纷表示居然还有这种操作

自用脚本，有些网站会检查是否打开控制台，循环往控制台写东西检查时间差（
https://gist.github.com/Namorzyny/e07395e9454c92989c1dcb4484a4cf9c

**Comment by xiaofeiTM233** [comment]
> 自用脚本，有些网站会检查是否打开控制台，循环往控制台写东西检查时间差（ https://gist.github.com/Namorzyny/e07395e9454c92989c1dcb4484a4cf9c

可以的，偷来了（doge）
