### ISSUE TITLE
[Bug] 超长日语字幕挤出屏幕

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#151]
### 问题描述

![6472D373-4A88-40D3-AD33-A805BEF620CD](https://github.com/ba-archive/blue-archive/assets/9006264/2fcb1c54-f2b0-423d-a580-9933871433bc)

### 问题位置

--

**Comment by diyigemt** [comment]
为什么按钮这么小字这么大

**Comment by Mark9804** [comment]
可能是全屏的时候字号没有跟着一起动态调节

**Comment by Mark9804** [comment]
这个没法修吧，算了

**Comment by diyigemt** [comment]
夸夸
