### ISSUE TITLE
[Enhancement] 主站两个 player 组件整合成一个

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#166]
### 功能描述

太唐了，我怎么写出这种东西来的

https://github.com/ba-archive/blue-archive/blob/main/apps/blue-archive-story-viewer/src/components/StoryViewer.vue

https://github.com/ba-archive/blue-archive/blob/main/apps/blue-archive-story-viewer/src/components/archive/StudentStoryPlayer.vue

prerequisite of #147, #158

**Comment by shelter-shadow** [comment]
推了一个pr (写完了才发现这个页面上能 link 新的 branch)
