### ISSUE TITLE
[Bug] Live2D 每句话的等待时间过长

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/blue-archive#17]
### 问题描述

我感觉可能是 setTimeout 开始计时的时间不对。体香1的 L2D 开头部分特别明显，甚至能等到📮对玩家笑一下。正常应该无缝衔接的

https://www.bilibili.com/video/BV1qY411f72B?t=137.4

https://www.bilibili.com/video/BV1CM411w7si?t=99.7

应该是从场景切换开始就进行计时，而不是场景播放完成后。

我记得 L2D 后来是灼光写的，就灼光看着修一下吧，不是的话甩给负责 L2D 层的组员

### 问题位置

100532:58

**Comment by diyigemt** [comment]
@Mark9804 宝贝你确定吗，我目押yuuka笑完都是11s左右开始说话的啊

**Comment by Mark9804** [comment]
那我到时候再看看
