### ISSUE TITLE
[Bug] 当学生模型 跳起来(?) 后模型 位置变高

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/blue-archive#18]
### 问题描述

rt
当学生 惊讶到跳起来 时模型位置变高并
不会自动回位
到log里回放几次后更明显
正常：
![img](https://user-images.githubusercontent.com/55832499/229276198-b43f4649-bab8-4289-b13a-54878892d2de.png)
不知怎么的遥香就长高了：
![img](https://user-images.githubusercontent.com/55832499/229276237-a75b6cd1-91ca-4cc7-81f7-f2690690746e.png)
后面发现甚至：
![img](https://user-images.githubusercontent.com/55832499/229276268-073b7d8c-d993-4a9c-a14f-8692c4c12603.png)

### 问题位置

200252

**Comment by diyigemt** [comment]
@~[ourandream](https://github.com/ourandream) 这个应该是跳转的bug, 原来的action是没问题的, 但跳转会导致原来的action被覆盖, 这就导致人物在比原来高的位置又执行了一遍jump, 这样自然会越来越高
---
@~[xiaofeiTM233](https://github.com/xiaofeiTM233) 意思就是log里跳转让他跳了2下是吧
---
@~[ourandream](https://github.com/ourandream) 意思是log让她第一次跳到半空就停下来, 然后又在错误的位置开始第二次跳的动作
---
@~[xiaofeiTM233](https://github.com/xiaofeiTM233) 又看了一下发现点击有跳动的log的前后2个log都会触发跳动，是否可以看一下是不是读取逻辑有问题（实际上是自己懒）
![image](https://user-images.githubusercontent.com/55832499/229292943-34525c13-bc26-4693-bd7b-6dc2867af067.png)
可以自己试着放一下，从左移入窗口是上一个动作，而这个动作仅仅是Surprise特效的
~~再次换了个测法试了试，问题是出在切的是没有跳动的格子，但是任然执行了跳动，并且是2个一起~~
~~我还以为我记错了又去测了一次，每次切log回去的时候特意跳等了3秒让他跳完
模型还是会越来越高，一次大概高5px左右~~

读取逻辑可能确实有点问题
以至于可以：
![image](https://user-images.githubusercontent.com/55832499/229293254-561d86e5-5b3c-462e-b227-8d81543d2eeb.png)


正常播放（隔2个log）就没出现此类问题

**Comment by diyigemt** [comment]
@Mark9804 宝贝有时间可以试试吗，估计和 #46 差不多

**Comment by Mark9804** [comment]
复现不出，就当修了吧，夸夸
