### ISSUE TITLE
[Bug] 页面失去焦点后大概率无法正常播放

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#187]
### 问题描述

--

### 问题位置

--

**Comment by Mark9804** [comment]
要不这样，失焦只影响auto属性，不直接干预播放

**Comment by Mark9804** [comment]
感觉像这里 https://github.com/ba-archive/blue-archive/blob/78d361674af4db4eee3a48b9c00fe48eaa4df654/lib/ba-story-player/lib/index.ts#L886-L897

**Comment by Mark9804** [comment]
不能响应点击时间，但是 auto 有概率可以继续

**Comment by Mark9804** [comment]
暂时把页面可见性监听下了吧要不
<img width="757" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/7d93494c-f791-4940-ae00-a9dd63a03eb6">

**Comment by diyigemt** [comment]
那就去了呗

**Comment by xiaofeiTM233** [comment]
我拉了最新分支也会这样，上次说的，全屏必须失去焦点才能继续播放（

**Comment by diyigemt** [comment]
@Mark9804 所以还原监听失焦机制然后把时间改回去算了

**Comment by Mark9804** [comment]
能播就行
