### ISSUE TITLE
[Bug] 人物特效 `a` 导致播放卡死

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#200]
### 问题描述

100793:31 

<img width="1116" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/66ffaaf0-4dd6-4c78-bea9-53cb5f838e74">

### 问题位置

--

**Comment by Mark9804** [comment]
onComplete 没有执行

**Comment by diyigemt** [comment]
哪段的剧情啊
我感觉同一个位置的a和h不会出现在同一个script里的

**Comment by Mark9804** [comment]
100793:31 宝贝

**Comment by Mark9804** [comment]
h不是我们觉得没有用吗

**Comment by diyigemt** [comment]
草 没印象了，那为什么之前不会卡住

**Comment by Mark9804** [comment]
我也想问这个问题 为什么之前不会卡住

我感觉这个结构和之前的差不多啊

**Comment by diyigemt** [comment]
我感觉这个结构和之前的差不多啊

**Comment by Mark9804** [comment]
还是会卡住啊

**Comment by Mark9804** [comment]
是不是有其他原因
