### ISSUE TITLE
[Bug] 左侧菜单刷新时出现，然后迅速消失

### ISSUE THREAD

**Issue by weiby3** [ba-archive/blue-archive#204]
### 问题描述

刷新时能看到左侧菜单一会。
![image](https://github.com/ba-archive/blue-archive/assets/30197106/4ca8f835-8755-42e9-b66e-ccaa67e29825)
随后菜单就消失了。
![image](https://github.com/ba-archive/blue-archive/assets/30197106/0cecbed4-76bd-41b1-8333-26208208d670)
分辨率换回正常的1920*1080也是这样。
刷新时手快能点到菜单项，也能进入对应页面，但菜单还是一样消失。

### 问题位置

https://blue-archive.io/

**Comment by Mark9804** [comment]
您好，没有办法复现

能麻烦看一下F12的控制台是否有报错吗

**Comment by weiby3** [comment]
![image](https://github.com/ba-archive/blue-archive/assets/30197106/b5e51d47-54aa-4bdf-bd0d-222c0047ddb2)
控制台只有这个脚本没加载，应该是被广告拦截了

**Comment by weiby3** [comment]
找到原因了，是去广告脚本误伤了。
装这个脚本就复现了。
https://sleazyfork.org/zh-CN/scripts/443290-adblock4limbo

**Comment by xiaofeiTM233** [comment]
所以说应该先禁用所有扩展或使用无痕模式测试一次再反馈的……

**Comment by Mark9804** [comment]
了解了，这边会看一下是触发了哪条规则

**Comment by weiby3** [comment]
> 所以说应该先禁用所有扩展或使用无痕模式测试一次再反馈的……

刚刚才想起来无痕模式复现。
不过倒是可以改一下问题模板，推荐无痕模式复现了再发issue。

**Comment by xiaofeiTM233** [comment]
> 刚刚才想起来无痕模式复现。 不过倒是可以改一下问题模板，推荐无痕模式复现了再发issue。

你无痕模式也复现吗

有的用户在无痕模式也会启用扩展，比如我，是不是也允许了在此模式下启用扩展？
![image](https://github.com/ba-archive/blue-archive/assets/55832499/26b35a73-9b95-4c4d-aa85-98be9519dc20)

**Comment by Mark9804** [comment]
无痕模式对于部分用户来说算比较高级的功能了，不能按照程序员思维一味提高反馈门槛

**Comment by weiby3** [comment]
> > 刚刚才想起来无痕模式复现。 不过倒是可以改一下问题模板，推荐无痕模式复现了再发issue。
> 
> 你无痕模式也复现吗
> 
> 有的用户在无痕模式也会启用扩展，比如我，是不是也允许了在此模式下启用扩展？ ![image](https://user-images.githubusercontent.com/55832499/278647161-26b35a73-9b95-4c4d-aa85-98be9519dc20.png)

少字了，我在无痕模式发现网站正常才尝试关掉去广告脚本，然后就发现原因了。

**Comment by xiaofeiTM233** [comment]
> 无痕模式对于部分用户来说算比较高级的功能了，不能按照程序员思维一味提高反馈门槛

我觉得这个应该归为常识，能上Github发issue肯定有能力关闭所有扩展及测试无痕模式甚至换设备换浏览器测试了（吧）
