### ISSUE TITLE
[Bug] 100796 莫名报错找不到选项，最后一句话被吞掉

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#206]
### 问题描述

100796:85

直接从这里开始测

看不到最后一句的 `因为这种理所当然的事情被责怪，我也感觉有点不好意思了……`

### 问题位置

--

**Comment by Mark9804** [comment]
https://github.com/ba-archive/blue-archive/blob/0bd38a1c47ecadb43b8682bcc6848479d291aa91/lib/ba-story-player/lib/layers/translationLayer/index.ts#L444-L450

**Comment by Mark9804** [comment]
```json
{
      "TextJp": "人として当たり前のことで怒られて、ちょっと恥ずかしくなったわ……。",
      "TextCn": "因为这种理所当然的事情被责怪，我也感觉有点不好意思了……",
      "TextKr": "",
      "TextEn": "",
      "TextTh": "",
      "TextTw": "",
      "GroupId": 1007906,
      "SelectionGroup": 0,
      "BGMId": 0,
      "Sound": "SFX_Emoticon_Motion_Upset",
      "Transition": 0,
      "BGName": 0,
      "BGEffect": 0,
      "PopupFileName": "",
      "ScriptKr": "#na;미사카;뭔가 생각지도 않았던 곳에서……. 좀 창피해졌네…….",
      "VoiceJp": "",
      "Unsure": false
    }
```

**Comment by Mark9804** [comment]
上面这个被识别成 `effectonly` 了

**Comment by Mark9804** [comment]
> 上面这个被识别成 `effectonly` 了

这个我修了，但是为什么出现幽灵选项我不清楚，mt明天看看吧
<img width="451" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/64083be9-4930-4f2b-a4bc-b3aff49bc296">

**Comment by diyigemt** [comment]
![image](https://github.com/ba-archive/blue-archive/assets/41864956/46944de7-0649-4a96-8d9e-8abf65233527)
尾部多了个\n

**Comment by Mark9804** [comment]
天才
