### ISSUE TITLE
[Bug] 跳转 index 问题

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/blue-archive#22]
### 问题描述

那个历史记录跳转好像有点问题，我在上边的位置，点击跳转到“老师写完了吗”，直接出现了下一个选项
![QQ图片20230325222748](https://user-images.githubusercontent.com/38815993/227723393-fb82be9a-43d7-4be9-9237-f1ab7794e8f9.png)

实际上中间还有一段文字的
![QQ图片20230325222755](https://user-images.githubusercontent.com/38815993/227723397-361c9ae3-1aca-4216-888c-c6ab73121614.jpg)

### 问题位置

200252

**Comment by diyigemt** [comment]
@Mark9804 宝贝这个也是 #46

**Comment by Mark9804** [comment]
夸夸，看起来也解决了
