### ISSUE TITLE
[Enhancement] 鼠标指针移动到MomoTalk的选项上时背景颜色变灰

### ISSUE THREAD

**Issue by lihaohong6** [ba-archive/blue-archive#231]
### 功能描述

如题。目前指针移动到选项上时，除了指针的变化外没有任何提示。我觉得[bluearchive.wiki](https://bluearchive.wiki/wiki/Shiroko/MomoTalk)的背景颜色变成浅灰更舒服一些（虽然选中某个选项之后的深灰色很丑）。

![image](https://github.com/ba-archive/blue-archive/assets/12545295/08a7bb1d-58b0-4f5a-80b0-9fc7208bd21e)

刚刚在控制台测试了一下，一会发个PR。

### 具体操作

```
.select-options {
    .div {
        transition: background-color ease-in-out .3s;
    }
    .div:hover {
        background-color: lightgrey;
        transition: background-color ease-in-out .3s;
    }
}
```

**Comment by lihaohong6** [comment]
突然发现新加的这段不能在夜间模式用，我再看看怎么调整。

**Comment by Mark9804** [comment]
感谢，夜间模式可以用css变量解决，灰色可以参考这两张色卡
<img width="1444" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/88c7a9d1-8291-4441-833e-ba061079c27a">
<img width="1456" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/26737c42-ef44-4235-ae5d-f7484e944e39">
