### ISSUE TITLE
[Enhancement] 非中文剧情显示角色名和所属社团

### ISSUE THREAD

**Issue by lihaohong6** [ba-archive/blue-archive#234]
### 功能描述

如题，虽然游戏文本里有对应的角色名，但是目前非中文剧情只显示日语角色名和社团。

### 具体操作

看不太懂角色信息是哪来的，搜索也搜不出来，只能说一下大概的原理。
1. 提取游戏剧情文本中的ScriptKr的分号中间的部分
2. 对提取出的文本使用32位xxhash
3. 在`ScenarioCharacterNameExcelTable.json`中查找散列值

图是bluearchive.wiki的discord的viliml发的，这个对应关系也是ta发现的。
![image](https://github.com/ba-archive/blue-archive/assets/12545295/2b268183-ea2b-48e7-acaa-9daa6523692c)

**Comment by sctop** [comment]
感谢提供消息，最近在做对nx脚本里的人物信息查询，正好能用上。

**Comment by mark9804** [comment]
这个功能我们下个月看看

**Comment by mark9804** [comment]
已支持

<img width="924" alt="image" src="https://github.com/user-attachments/assets/3dd5205d-34e6-4877-8f0b-0e067c567f1f">
