### ISSUE TITLE
[Bug] 女仆爱丽丝的好感剧情: "女仆勇者的装备"的简介缺失中文翻译

### ISSUE THREAD

**Issue by Tony-Feng** [ba-archive/blue-archive#244]
### 问题描述

在女仆爱丽丝的好感剧情的网页界面中，"女仆勇者的装备"这一章，中文页面对应的简介目前显示日语（[https://blue-archive.io/archive/10066/story](https://blue-archive.io/archive/10066/story)）：
![image](https://github.com/ba-archive/blue-archive/assets/43994607/67122dea-66dc-447b-acfa-26dc6c8e4d9c)

### 问题位置

页面地址为：[https://blue-archive.io/archive/10066/story](https://blue-archive.io/archive/10066/story)，截图在问题描述中已经提供；对应的yml文件地址为：https://github.com/ba-archive/blue-archive/blob/main/apps/blue-archive-story-viewer/public/story/favor/10066/index.yml#L45-L58

**Comment by mark9804** [comment]
私密马赛 忘记翻了
