### ISSUE TITLE
水黑猫l2d没bgm

### ISSUE THREAD

**Issue by mark9804** [ba-archive/blue-archive#245]
### 问题描述

200363

### 问题位置

200363

**Comment by diyigemt** [comment]
好像只是单纯的BGMExcelTable不是最新的，但是我查cdn刷新记录当天确实刷新了，用的也是⚡🐏的源，现在去翻他的数据却是有的，很怪
总之已经更新成最新的了

**Comment by mark9804** [comment]
夸夸
