### ISSUE TITLE
[Enhancement] 电视机雪花特效 BG_TvNoise_Sound

### ISSUE THREAD

**Issue by mark9804** [ba-archive/blue-archive#256]
### 功能描述

2720349264 BG_TvNoise_Sound

https://www.bilibili.com/video/BV1cCxteBEPH?t=6.0

[[未校对]1003805.json](https://github.com/user-attachments/files/17329322/1003805.json)

**Comment by ChangeSuger** [comment]
稍微手搓了下电视机雪花的特效，头目可以看一下效果

[实战-电视机雪花特效 | PixiJS 6 Examples (pixijs-6-examples.vercel.app)](https://pixijs-6-examples.vercel.app/examples/03-tv-noise-sound/)

**Comment by mark9804** [comment]
不是哥们，你这有点快了😨

今天有点事，晚上回家我看看

**Comment by mark9804** [comment]
表现上没问题，可以先做进来，暂时不用太管性能问题
