### ISSUE TITLE
[Bug] firefox下对话框文字会上下跳动

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/blue-archive#33]
### 问题描述

![image](https://user-images.githubusercontent.com/71924104/221502497-0bd08f4d-973e-4170-9ec4-bf777ab9d857.png)
![image](https://user-images.githubusercontent.com/71924104/221502618-b086863d-1173-4f98-a20b-e196ff86bf2b.png)

目前chrome, via, android edge经过测试没有这种情况, 应该是firefox独有的bug.

### 问题位置

-

### 复现流程

这个看上去是 firefox 的文字引擎会对省略号进行转义（下面的省略号跳到中间了），如果确认是这个问题的话就是我们处理不了的东西了

---
可能是这个原因, 目前的解决办法是把省略号换成6个点......

---
Safari 也有这问题，，，

**Comment by Mark9804** [comment]
这个暂时不修了，省略号本来就是一个特殊符号，浏览器喜欢转就随它去吧
