### ISSUE TITLE
[Enhancement] 更新模糊匹配算法

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#35]
不用编辑距离算法了
https://github.com/zh-lx/pinyin-pro

**Comment by diyigemt** [comment]
宝贝 title格式是你定的

**Comment by Mark9804** [comment]
我知道 但要是不发出来的话我就真忘了

**Comment by Mark9804** [comment]
dcd791ca01f0c0e821a3b9cffc03bf556dd7f5cb
