### ISSUE TITLE
[Enhancement] 文字加粗标记 [b][/b]

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#44]
### 功能描述

32020:8 英文状态下的标记

<img width="1441" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/8a51ed9f-3738-4b16-99ff-9b13ae54d7df">

**Comment by diyigemt** [comment]
等下 还有个问题  这颜色不太对劲啊 应该只有最后的 及格/不及格 才有颜色 啊哈哈

**Comment by Mark9804** [comment]
至少能跑 夸夸

**Comment by diyigemt** [comment]
只在en下才会出现这两问题 好 low priority !

**Comment by Mark9804** [comment]
所以为什么en不一样呢

**Comment by diyigemt** [comment]
因为目前tag解析是伪AST 只能对付形如  [fontsize=xxx][color=xxxx]文字内容[/color][/fontsize]  这种连续嵌套情况

如果是 [fontsize=xxx]文字内容[color=xxxx]文字内容[/color][/fontsize] 这种就抓瞎了

目前打算上真正的AST了

啊哈哈

**Comment by Mark9804** [comment]
夸夸

**Comment by diyigemt** [comment]
一直盯着邮件 夸夸
