### ISSUE TITLE
[Bug] change-index 导致人物影分身

### ISSUE THREAD

**Issue by mark9804** [ba-archive/blue-archive#46]
### 问题描述

我的建议是触发 change-index 之后强制刷新所有人物

<img width="672" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/a912f4ec-d048-4153-ba7d-762cf29be75c">

### 问题位置

32020:237 转 32020:239
其他任意前后两个角色位置不一样的剧情单元

**Comment by diyigemt** [comment]
你说刷新 咋刷啊
![)0~ S06AGTG23VGB5A9@W 7](https://github.com/ba-archive/blue-archive/assets/41864956/0d62829c-9c66-433b-849d-1eda866afce6)
这玩意就是个累计的关系 只有重头跑到这才能知道现在有谁在哪
最好的办法是单独维护一个存了每个index有什么的列表，现在炼丹不也需要吗
总之backlog

**Comment by Mark9804** [comment]
夸夸

**Comment by diyigemt** [comment]
宝贝看看最新的feature/change-index分支
不太明白怎么复现

**Comment by Mark9804** [comment]
等到下周再看，周一周二我要交材料了

**Comment by Mark9804** [comment]
我感觉没问题，夸夸
