### ISSUE TITLE
[Enhancement] 当找不到特效作用 index 时，log error但是不抛出致命错误

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#47]
### 功能描述

nexon 是自由的

<img width="1183" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/a377cb04-edaf-417e-9cf3-1efb8b69f1e1">

![image](https://github.com/ba-archive/blue-archive/assets/9006264/4bbfa44a-281f-4b68-8115-6f3458eb7baa)

**Comment by diyigemt** [comment]
单独记录index真得写写了 #46 啊哈哈
