### ISSUE TITLE
[Bug] 在log界面上滑超出log范围时会关闭log

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/blue-archive#51]
### 问题描述

点开log界面，在log界面按下鼠标左键，将鼠标上滑至超出log范围，松开鼠标，log界面关闭

### 问题位置

任意位置

### 复现流程

1. 换一个不是蓝色的手机壳
2. 打开网页
3. 背景图片还是蓝色的

**Comment by Mark9804** [comment]
可能和 #24 是同一个问题

**Comment by Qzhihe** [comment]
收到！

Mark Chen ***@***.***> 于 2023年6月27日周二 23:40写道：

**Comment by Mark9804** [comment]
https://github.com/ba-archive/blue-archive/blob/787c8ce15cff03c818c119d2d9bb7fc1c20398c2/lib/ba-story-player/lib/layers/uiLayer/userInteract.ts#L58-L86
