### ISSUE TITLE
[Bug] 部分设备水宫子 l2d 语音无法播放

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#58]
### 问题描述

原因不明，我测的可以

### 问题位置

100716:18

### 复现流程

不知道

两个设备都没有
一加8pro h2os10 安卓10 chrome
win11 chrome

**Comment by xiaofeiTM233** [comment]
我昨天晚上看以为还在dev分支，只是语音忘传了，原来是播放有问题
刚刚测了，能够正常全屏的设备可以正常播放，全屏有框的不行，看看可不可以一起修
