### ISSUE TITLE
[Bug] ST 打不出字导致剧情无法继续

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#64]
### 问题描述

<img width="1920" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/dd3f27bb-cbd9-4144-9923-7ba9e506b6fc">

### 问题位置

31040:80

**Comment by diyigemt** [comment]
咱们真的需要测试了

**Comment by Mark9804** [comment]
测试说实话难找

我的想法是开个内测群，有意向的加群，给群友发 CloudFlare pages 的链接去测试，有问题的反馈

**Comment by diyigemt** [comment]
都是散装的测试，最多也就只能测到刚更新的内容，像这种底层更改导致旧的资源变化的很难测出来。
整理一下测试用例吧，快进到100%coverage

**Comment by xiaofeiTM233** [comment]
> 测试说实话难找
> 
> 我的想法是开个内测群，有意向的加群，给群友发 CloudFlare pages 的链接去测试，有问题的反馈

我想测最新进度但是你们的dev和实际进度不符啊（
dev分支好像都是已经可以放出来的东西了
而有时刚推dev，就推了主分支
感觉这个开发分支不算开发分支了（）

**Comment by Mark9804** [comment]
dev不就是这么用的吗，就是用来存放还没到推送窗口的变更的啊

**Comment by diyigemt** [comment]
有道理 应该专门有个bug-fix分支的
毕竟有时候真的需要临时修复一些东西，master又有保护

**Comment by Mark9804** [comment]
那开吧

**Comment by diyigemt** [comment]
我是指bug-fix分支应该直接从master上开出来 merge也merge到master和dev上

**Comment by Mark9804** [comment]
那确实
