### ISSUE TITLE
rfc: 播放器组件 css in js

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#69]
https://github.com/Marco-Prontera/vite-plugin-css-injected-by-js

好处：不需要单独引入一个 css 文件

坏处：性能略微下降，兼容性不知道

**Comment by diyigemt** [comment]
真的有必要吗

**Comment by Mark9804** [comment]
我不知道 我太菜了 呜呜

**Comment by luckyray-fan** [comment]
没有必要
