### ISSUE TITLE
[Bug] 剧情快速点击时偶发 BGM 重叠

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#74]
### 问题描述

100225 那边测的时候发现的，暂时不清楚触发条件，猜测出现在 BGM 切换的两个 index 之间

### 问题位置

100225

**Comment by diyigemt** [comment]
没复现欸
而且bgm那边是有限制的
![image](https://github.com/ba-archive/blue-archive/assets/41864956/47784374-a77b-4d9c-9419-7833eef1e1ed)

**Comment by xiaofeiTM233** [comment]
我这刚刚看的时候有复现，设备win7edge

**Comment by diyigemt** [comment]
夸夸

**Comment by Mark9804** [comment]
和系统还有浏览器无关吧 是不是某个地方生命周期出问题了 该发送的事件没发送或者该销毁的实例有概率没有销毁

**Comment by diyigemt** [comment]
我超复现了

**Comment by diyigemt** [comment]
稳定复现了，比如在100225开头 hina说完"就睡一会会"后切换窗口，让它冻结，过几秒再切回去就行

**Comment by xiaofeiTM233** [comment]
要不顺便看看，播放完后，音频仍然在播放的bug，是否也是这个原因

**Comment by diyigemt** [comment]
那个是因为播放完成后并不会停止bgm播放，~是feature~
顺便修了吧

**Comment by diyigemt** [comment]
fix at #79
