### ISSUE TITLE
Pixijs v7

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#88]
~~pixijs 都卷到 v8 了，想必 v7 应该已经很稳定了吧~~

## 升级原因

1. 官方的终于支持了按需引入模块和 tree shaking，对播放器整体体积减小有一定帮助
2. 官方规整了导出，代码更清楚

```ts
import { Rectangle, settings, ALPHA_MODES, utils } from '@pixi/core';

const { string2hex } = utils;
```

3. #30 
4. ~~冲 KPI~~ 经讨论决定设置播放器状态管理库，将 UI 层的设计改为状态驱动。都准备重构了，要重构就彻底点

## 分支

开一个 `refactor/pixi-v7` 分支开始贡献

## 兼容性测试

今年四月的 [小春 2048](https://github.com/ba-archive/koharu-2048)：Live2D 播放测试通过，音效播放测试通过

未测试：特效 filters （官方声称完全支持）

## 留存问题

- [ ] [需要魔改 pixi-spine 以保证 404 等错误能正常抛出](https://github.com/pixijs/spine/issues/498)

* 其他问题在本 issue 内提出

## 单元测试靶场

待更新

## 分工

- [ ] **背景层 bgLayer**：待认领
- [ ] **角色层 characterLayer**：待认领
- [ ] **特效层 effectLayer**：待认领
- [ ] **L2D 层 l2dLayer**：待认领
- [ ] **声音层 soundLayer**：待认领

**Comment by diyigemt** [comment]
宝贝 这玩意咋改啊
要不先开个已经升级好的分支

**Comment by Mark9804** [comment]
还有三个 deprecated 

<img width="477" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/a4f2898a-de53-41b3-8adb-1023063419c7">

**Comment by diyigemt** [comment]
第一个是@pixi/filter-advanced-bloom@5.1.1导致的，和我们没关系
第二个有关系
第三个是pixi-spine@4.0.5导致的，和我们没关系
